# Site settings
title: TONE-GEEK
email: info@tone-geek.com
description: > # this means to ignore newlines until "baseurl:"
  tone-geek.
baseurl: "/tone-geek-website/" # the subpath of your site, e.g. /blog/
url: "http://www.tone-geek.com" # the base hostname & protocol for your site
twitter_username: tone-geek
github_username:  tone-geek

# Build settings
markdown: kramdown
